services:
  mysql:
    image: mysql:8.0
    container_name: cp476_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cp476_forum
      MYSQL_USER: cp476
      MYSQL_PASSWORD: cp476pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: